config/routes.rb
Spreads::Application.routes.draw do
  resources :leagues

  get "test/lines"

  resources :games
  resources :pick_sets

  devise_for :users

  match 'standings/' => 'standings#index'
  resources :weeks

  root :to => "pick_sets#index"

end

app/models/pick_set.rb
class PickSet < ActiveRecord::Base
  has_many :picks, :dependent => :destroy
  belongs_to :user
  belongs_to :week

  # the :reject_if prevents every pick from being saved since only selected picks will have those attributes inside of a hidden field
  # seems a little hacky, should look into changing at some point
  accepts_nested_attributes_for :picks, :reject_if => lambda { |a| a[:is_home].blank? && a[:spread].blank? && a[:over_under].blank? && a[:is_over].blank? }

#  validate :number_of_picks

  def number_of_picks
    errors.add(:base, "You cannot have more than 3 picks in a week") if self.picks.size > 3
  end

  def check_for_non_picks
    if Week.find(self.week_id).end_date < Week.current.first.start_date
      games = Game.find_all_by_week_id(self.week_id).size
#      if self.picks.size < 3
      if self.picks.size < games
        losses = games - self.picks.size
        losses.times {Pick.create!(:spread => 0, :result => -1, :game_id => 0, :pick_set_id => self.id, :over_under => 0, :over_under_result => -1)}
      end
      self.picks.each do |p|
        unless p.complete
          if p.spread.nil?
            p.update_attributes(:spread => 0, :result => -1)
          else
            p.update_attributes(:over_under => 0, :over_under_result => -1)
          end
        end
      end
    end
  end

  def self.all_picks_in(week=Week.current.first)
    games = Game.find_all_by_week_id(week.id).size
    pick_sets = find_all_by_week_id(week.id)
    pick_total = 0
    pick_sets.each do |ps| 
      ps.picks.each do |p|
        pick_total += 1 if p.complete
      end
    end
    if pick_total >= User.active.size * games 
      return true
    else
      return false
    end
  end
end

app/controllers/pick_sets_controller.rb
class PickSetsController < ApplicationController
  before_filter :authenticate_user!

  # GET /pick_sets
  # GET /pick_sets.xml
  def index
    @current_pick_set = Week.current.first.pick_sets.where("user_id = #{current_user.id}").first
    # @league_pick_sets = User.where("id != #{current_user.id}") 
    @week = Week.current.first
    @title = "Week #{@week.name} picks"
    @total_games = Game.find_all_by_week_id(@week.id).size

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pick_sets }
    end
  end

  # GET /pick_sets/1
  # GET /pick_sets/1.xml
  def show
    @pick_set = PickSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pick_set }
    end
  end

  # GET /pick_sets/new
  # GET /pick_sets/new.xml
  def new
    if current_user.has_picks_for_this_week
      redirect_to pick_sets_url, :alert => 'You can\'t create picks for this week anymore. View or add picks below.'
    else
      @pick_set = PickSet.new
      @games = Game.with_spreads
      @week = Week.current.first
      @title = "Week #{@week.name} picks"

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @pick_set }
      end
    end
  end

  # GET /pick_sets/1/edit
  def edit
    @pick_set = PickSet.find(params[:id])
    @games = Game.with_spreads(current_user)
    @week = Week.current.first
    @title = "Week #{@week.name} picks"
  end

  # POST /pick_sets
  # POST /pick_sets.xml
  def create
    @pick_set = PickSet.new(params[:pick_set])
    @pick_set.user_id = current_user.id
    @pick_set.week_id = Week.current.first.id
    @games = Game.with_spreads
    @week = Week.current.first
    @title = "Week #{@week.name} picks"

    respond_to do |format|
      if @pick_set.save
        format.html { redirect_to(pick_sets_url, :notice => 'Pick set was successfully created.') }
        format.xml  { render :xml => @pick_set, :status => :created, :location => @pick_set }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pick_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pick_sets/1
  # PUT /pick_sets/1.xml
  def update
    @pick_set = PickSet.find(params[:id])
    @games = Game.with_spreads(current_user)
    @week = Week.current.first
    @title = "Week #{@week.name} picks"

    respond_to do |format|
      if @pick_set.update_attributes(params[:pick_set])
        format.html { redirect_to(pick_sets_url, :notice => 'Pick set was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pick_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pick_sets/1
  # DELETE /pick_sets/1.xml
  def destroy
    @pick_set = PickSet.find(params[:id])
    @pick_set.destroy

    respond_to do |format|
      format.html { redirect_to(pick_sets_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/pick_sets_helper.rb
module PickSetsHelper
end

app/views/pick_sets/_form.html.erb
<% if @games %>
  <% content_for :head do %>
    <%= javascript_include_tag 'pick_controls' %>
  <% end %>
  
  <%= form_for(@pick_set) do |f| %>
    <% if @pick_set.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pick_set.errors.count, "error") %> prohibited your picks from being saved:</h2>

        <ul>
        <% @pick_set.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <ul id="gameList" style="list-style: none">
      <% @games.each do |game| %>
        <% game.spread = "-2.5" if game.id = 272 %>
        <% game.over_under = "45.5" if game.id = 272 %>
        <li id="<%= game.id %>" class="<%= cycle('shade', ' ') %>">
        <% if game.spread != "n/a" && game.date > Time.now - 1.hour %>
          <%= f.fields_for(:picks, Pick.new) do |p| %>
            <% if game.spread != "pick" %>
              <div class="teamLine">
                <%= check_box_tag("pick_#{game.id}_0", '1', false, :class => 'pick') %>
                <span class="team away"><%= game.away %></span>
                <span class="spread">
                  <% if game.spread != "0" %>
                    <%= game.spread.to_f * -1 > 0 ? '+' : '' %><%= game.spread.to_f * -1 %>
                  <% else %>
                    <%= game.spread.to_f %>
                  <% end %>
                </span>
              </div>
              <div class="teamLine">
                <%= check_box_tag("pick_#{game.id}_1", '1', false, :class => 'pick') %>
                <span class="team home"><%= game.home %></span>
                <span class="spread"><%= game.spread.to_f > 0 ? '+' : '' %><%= game.spread.to_f %></span>
              </div>
            <% else %>
              <div class="teamLine">
                <%= game.away %>
              </div>
              <div class="teamLine">
                <%= game.home %>
              </div>
            <% end %>
            <% unless game.over_under == "n/a" %>
              <div class="over_under_container">
                Over/Under: <span class="over_under"><%= game.over_under %></span><br />
                <%= check_box_tag("pick_ou_#{game.id}_0", '1', false, :class => 'over_under_pick') %>
                <span class="over">Over</span><br />
                <%= check_box_tag("pick_ou_#{game.id}_1", '1', false, :class => 'over_under_pick') %>
                <span class="under">Under</span>
              </div>
            <% end %>
            <%= p.hidden_field :is_home, :class => 'set_team' %>
            <%= p.hidden_field :spread, :class => 'set_spread' %>
            <%= p.hidden_field :is_over, :class => 'set_is_over' %>
            <%= p.hidden_field :over_under, :class => 'set_over_under' %>
            <%= p.hidden_field :game_id, :value => game.id %>
          <% end %>
        <% else %>
          <div class="gameOff"><h2>OFF</h2></div>
          <div class="teamLine">
            <%= game.away %>
          </div>
          <div class="teamLine">
            <%= game.home %>
          </div>
        <% end %>
        </li>
      <% end %>
    </ul>

    <div class="actions" style="margin:12px 0">
      <%= f.submit 'Submit', :onclick => 'return confirm("Are you sure you want to submit these picks? Once submitted they cannot be changed.")' %>
    </div>
  <% end %>
<% else %>
  <h2>Problem connecting to data source, please check back later.</h2>
<% end %>

<% comment do %>
<p>Lines will be available shortly...</p>
<% end %>

app/views/pick_sets/edit.html.erb
<h1><%= "Week #{@week.name} Picks" %></h1>

<%= render 'form' %>

app/views/pick_sets/index.html.erb
<h1><%= "Your Week #{@week.name} Picks" %></h1>

<% if @current_pick_set %>
  <ul id="weeksPicks">
    <% comment do %>
      <% if @current_pick_set.picks.size < 3 %>
        <li class="pickAlert">
        <% @picks_left = 3 - @current_pick_set.picks.size;
           @pick_or_picks = @picks_left > 1 ? 'picks' : 'pick' %>
           <h2><%= "You need to make #{@picks_left} more #{@pick_or_picks} for this week." %></h2>
          <%= link_to 'Add picks', edit_pick_set_path(@current_pick_set) %>
        </li>
      <% end %>
    <% end %>

    <% if @current_pick_set.picks.collect(&:complete).delete_if {|x| !x}.size < @total_games %>
      <%= link_to 'Add/Modify picks', edit_pick_set_path(@current_pick_set) %>
    <% end %>
    <% @current_pick_set.picks.each do |pick| %>
      <li class="pick">
        <%= pick.team %>
        <% unless pick.spread.nil? %>
          <%= pick.spread > 0 ? "+" : '' %><%= pick.spread %>
        <% end %>
        (<% if pick.is_home %>
          vs <%= Game.find(pick.game_id).away %>
        <% else %>
          at <%= Game.find(pick.game_id).home %>
        <% end%>
        )
        <% if pick.spread.nil? %>
          <span style="color: red">NO SPREAD PICK YET</span>
        <% end %> 
        <br />
        <% if pick.over_under.nil? %>
          <span style="color: red">NO OVER/UNDER PICK YET</span>
        <% else %>
          <%= pick.over_under %> <%= pick.is_over? ? "Over" : "Under" %>
        <% end %>
      </li>  
    <% end %>
  </ul>
<% else %>
  <div class="pickAlert"><h2>You haven't made any picks for this week.</h2>
  <%= link_to "Make picks for Week #{@week.name}", new_pick_set_path %></div>
<% end %>

app/views/pick_sets/new.html.erb
<h1><%= "Week #{@week.name} Picks" %></h1>

<%= render 'form' %>

app/views/pick_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @pick_set.user_id %>
</p>

<p>
  <b>Week:</b>
  <%= @pick_set.week %>
</p>


<%= link_to 'Edit', edit_pick_set_path(@pick_set) %> |
<%= link_to 'Back', pick_sets_path %>